/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_a8043_simpleCode_tools_windows_Native */

#ifndef _Included_org_a8043_simpleCode_tools_windows_Native
#define _Included_org_a8043_simpleCode_tools_windows_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    getAllWindows
 * Signature: ()Lcn/hutool/json/JSONArray;
 */
JNIEXPORT jobject JNICALL Java_org_a8043_simpleCode_tools_windows_Native_getAllWindows
  (JNIEnv *, jclass);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    getWindowTree
 * Signature: (Ljava/lang/String;)Lcn/hutool/json/JSONObject;
 */
JNIEXPORT jobject JNICALL Java_org_a8043_simpleCode_tools_windows_Native_getWindowTree
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    clickButton
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a8043_simpleCode_tools_windows_Native_clickButton
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    clickElement
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a8043_simpleCode_tools_windows_Native_clickElement
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    inputText
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a8043_simpleCode_tools_windows_Native_inputText
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    activateWindow
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a8043_simpleCode_tools_windows_Native_activateWindow
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    closeWindow
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a8043_simpleCode_tools_windows_Native_closeWindow
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    setChecked
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a8043_simpleCode_tools_windows_Native_setChecked
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    selectElement
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a8043_simpleCode_tools_windows_Native_selectElement
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    scrollElement
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a8043_simpleCode_tools_windows_Native_scrollElement
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     org_a8043_simpleCode_tools_windows_Native
 * Method:    pressKey
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_a8043_simpleCode_tools_windows_Native_pressKey
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
